# Generated by Django 5.1.1 on 2024-09-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cloth_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='usecount',
            field=models.IntegerField(default=0),
        ),
    ]
