# Generated by Django 5.1.1 on 2024-09-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_cloth_usecount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
