# Generated by Django 5.1.1 on 2024-09-29 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_cloth_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
